version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_FRONTEND_URL: "https://localhost:8443/auth/"
      PROXY_ADDRESS_FORWARDING: 'true'

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - 8443:8443
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/certs:/etc/ssl/private
    depends_on:
      - keycloak